import Head from 'next/head'
import SectionOne from '../components/home/SectionOne'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Staging</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SectionOne />


    </div>
  )
}
